# config for scraps snakemake pipeline #
 
DATA: 
# Data folder containing FASTQs
  "/beevol/home/gillena/projects/10x_3p/platform_test_data"

# results directory
RESULTS:
  "../results_202105"

# path to STAR executable
STAR:
  "/beevol/home/gillena/build/STAR-2.7.8a/bin/Linux_x86_64/STAR"

# path to STAR genome index
STAR_INDEX:
  "/beevol/home/hemegroup/ref/cr2020A_star"
  
# path to Chromium V3 whitelist
WHITELIST_V3:
  "/beevol/home/hemegroup/ref/3M-february-2018.txt"

# path to Chromium V2 whitelist
WHITELIST_V2:
  "/beevol/home/hemegroup/ref/737K-august-2016.txt"

POLYA_SITES:
# polya_db 3 on GRCh38 with 5 bases upstream and 3 bases
# downstream slop relative to annotated cleavage site
   "ref/polyadb32.hg38.saf.gz"
   
#POLYA_FORMAT:
# SAF or GTF, currently auto detecting filename .saf or .saf.gz, case-insensitive
#   "SAF"

# TSV relating all sequenced libraries to sane capture names
FASTQS:
  "sample_fastqs.tsv"
    
# TSV with per-capture metadata and sample ID
CAPTURES:
  "sample_captures.tsv"

R1_SAMPLES:
# Sample basenames
  - PT46T_miseq
  - PT46L_miseq
  - PT46L_nextseq
  - HTB1261DX_hiseq2500
  - HTB1261DX_hiseq2500
  - HTB1261DX_hiseq2500
  - HTB1261DX_hiseq2500
  - HTB1261RL_hiseq2500
  - HTB1261RL_hiseq2500
  - HTB1261RL_hiseq2500
  - HTB1261RL_hiseq2500
  - HTB1261DX_novaseq
  - HTB1261RL_novaseq

R2_SAMPLES:
  - PT46T_miseq
  - PT46L_miseq
  - PT46L_nextseq
  - HTB1261DX_hiseq2500
  - HTB1261DX_hiseq2500
  - HTB1261DX_hiseq2500
  - HTB1261DX_hiseq2500
  - HTB1261RL_hiseq2500
  - HTB1261RL_hiseq2500
  - HTB1261RL_hiseq2500
  - HTB1261RL_hiseq2500
  - HTB1261DX_novaseq
  - HTB1261RL_novaseq
  - PT46L_hiseq4000
  - PT46T_hiseq4000
