# config for scraps snakemake pipeline #

# results directory
RESULTS:
  "results"

# path to STAR executable, if not in PATH
STAR:
  "STAR"

# path to STAR genome index
STAR_INDEX:
  "index/cr2020A_star"
  
# path to Chromium V3 whitelist
WHITELIST_V3:
  "ref/3M-february-2018.txt"

# path to Chromium V2 whitelist
WHITELIST_V2:
  "ref/737K-august-2016.txt"

POLYA_SITES:
# polya_db 3 on GRCh38 with 5 bases upstream and 3 bases
# downstream slop relative to annotated cleavage site
  "ref/polyadb32.hg38.saf.gz"
   
#POLYA_FORMAT:
# SAF or GTF, currently auto detecting filename .saf or .saf.gz, case-insensitive
#   "SAF"

# TSV relating all sequenced libraries to sane capture names
FASTQS:
  "sample_fastqs.tsv"
    
# TSV with per-capture metadata and sample ID
CAPTURES:
  "sample_captures.tsv"

R1_SAMPLES:
# Sample basenames
  - test

R2_SAMPLES:
  - test