on:
  push:
  pull_request:
    branches:
      - master

name: snakemake-run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
  
    - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
          mamba-version: "*"
          channels: bioconda,conda-forge,defaults
          channel-priority: true
          activate-environment: scraps_conda
          environment-file: environment.yml

    - shell: bash -el {0}
        run: |
          snakemake -npr --configfile config.yaml 

