on:
  push:
  pull_request:

name: snakemake-run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
  
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: bioconda,conda-forge,defaults
        channel-priority: true
        activate-environment: scraps_conda
        environment-file: scraps_conda.yml

    - shell: bash -el {0}
      run: |
        snakemake -npr --configfile config.yaml 

